# Generated by Django 4.2.5 on 2025-02-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('degree', models.CharField(max_length=255)),
                ('job_experience', models.TextField()),
                ('contact_time', models.TimeField()),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
